### ISSUE TITLE
Crash to Desktop on Launch

### ISSUE THREAD

**Issue by AsherShadowstep** [NagaseYami/PotionCraftAutoHaggle#1]
- I am using the version of BepInEx you linked in your mod. (https://github.com/BepInEx/BepInEx/releases/tag/v5.4.21)

- My game version is 1.0.5.

1) I extracted BepInEx to my Steam folder.
2) I ran the game to set up BepInEx's file structure
3) I placed your mod in its Plugins folder.
4) I am ONLY using your mod.

CTD

![Potion Craft Folder](https://user-images.githubusercontent.com/122832727/212764654-98bd12a5-8708-43dc-b575-7b1a2826dada.png)

![inside bepinex](https://user-images.githubusercontent.com/122832727/212764632-fe16c39c-a4e9-469f-8d2e-496fe2ad787a.png)

![bepinex plugins](https://user-images.githubusercontent.com/122832727/212764641-b9e01154-c2b7-4711-9cf6-b28ba7e1fe89.png)

![Screenshot 2023-01-16 155116](https://user-images.githubusercontent.com/122832727/212764819-b3d82a33-333d-4af2-9fb4-93409d195c7c.jpg)

**Comment by NagaseYami** [comment]
> My game version is 1.0.5.

My mod is only for 1.01.
You should check this out.

https://www.nexusmods.com/potioncraftalchemistsimulator/mods/28

![image](https://user-images.githubusercontent.com/23649435/212810228-8883c5c5-d161-4b14-a38f-d7de77a9ba3d.png)
